# Generated by Django 5.1.7 on 2025-03-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('diploma', models.CharField(choices=[('Среднее образование', 'Среднее образование'), ('Бакалавр', 'Бакалавр'), ('Магистр', 'Магистр'), ('Кандидат наук', 'Кандидат наук'), ('Доктор наук', 'Доктор наук')], max_length=50)),
                ('position', models.CharField(default='Не определено', max_length=100)),
                ('salary', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True)),
            ],
        ),
    ]
