# Generated by Django 5.1.7 on 2025-03-14 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Tags',
        ),
    ]
