# Generated by Django 5.1.7 on 2025-03-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezkafilmsmodel',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
