# Generated by Django 5.1.7 on 2025-03-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0002_rezkafilmsmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rezkafilmsmodel',
            name='image',
        ),
    ]
